name: CI/CD Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - dev
  workflow_dispatch: 

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        run: mvn compile

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Run Tests
        run: mvn clean test
      - name: Generate JaCoCo Coverage Report
        run: mvn jacoco:report
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: surefire-reports
          path: target/surefire-reports/
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: target/site/jacoco/

  package:
    name: Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build Package
        run: mvn clean package
      - name: Upload Package
        uses: actions/upload-artifact@v3
        with:
          name: packaged-app
          path: target/idatt2002demo-1.0-SNAPSHOT-jar-with-dependencies.jar

  deployPages:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
      
      - name: Generate Javadoc and Coverage Reports
        run: |
          mvn javadoc:javadoc
          mvn jacoco:report
          mkdir -p page
          cp -rf target/site/* page/
          cp -rf target/site/jacoco/* page/
      
      - name: Setup Pages
        uses: actions/configure-pages@v5
      
      - name: Upload index.html
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'page/'
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
